<<<<<<< HEAD
# 예외처리를 하게 되면, 오류가 발생이 되어도
# 프로그램이 종료되지 않음.
# 프로그램 구현중에 잘못된 코드 : 구문오류
# 런타임 오류 : 프로그램 실행 중에 발생하는 오류

while True: # 오류가 발생가능 지점
    print('[ 리스트 출력 프로그램 ]')
    try:
        num = int(input('숫자를 입력하세요.>> '))
        a_list = [1,2,3,4,5]
        for i in range():
            print(a_list[i])
    except:
        print('구문에 오류가 났습니다.')
=======
# 예외처리를 하게 되면, 오류가 발생이 되어도
# 프로그램이 종료되지 않음.
# 프로그램 구현중에 잘못된 코드 : 구문오류
# 런타임 오류 : 프로그램 실행 중에 발생하는 오류

while True: # 오류가 발생가능 지점
    print('[ 리스트 출력 프로그램 ]')
    try:
        num = int(input('숫자를 입력하세요.>> '))
        a_list = [1,2,3,4,5]
        for i in range():
            print(a_list[i])
    except:
        print('구문에 오류가 났습니다.')
>>>>>>> 992ee3a (파이썬 수업내용)
